language: python
python:
  - "2.6"
  - "2.7"
  - pypy
matrix:
    allow_failures:
        - python: pypy
# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
before_script:
  - pip install python-coveralls
  - pip install pytest-cov
# command to run tests
script: py.test --cov modules --cov-report term-missing
after_success:
  - coveralls