language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "python setup.py"
  - "pip install -U pytest"
# command to run tests
script: py.test